name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer exec --verbose phpcs -- --standard=PSR12 src bin
      - name: My project check
        with:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
